#
# Warning: you may need more libraries than are included here on the
# build line.  The agent frequently needs various libraries in order
# to compile pieces of it, but is OS dependent and we can't list all
# the combinations here.  Instead, look at the libraries that were
# used when linking the snmpd master agent and copy those to this
# file.
#

CC=gcc

#make can auto know the *.c file, here we just change the OBJS1
#OBJS=snmp_test-ok.o
OBJS=get-route-table.o msh_ipRouteTable.o \
topology-discovery.o topology-queue.o

#here also should be changed with your purpose for target 
TARGETS=runsnmp

BUILDLIBS=`net-snmp-config --libs`

all: $(TARGETS)

$(TARGETS): $(OBJS)
	$(CC) -o $(TARGETS) $(OBJS) $(BUILDLIBS)

clean:
	rm $(OBJS) $(TARGETS)
